app = "finly-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  DATABASE_PATH = "/data/database.sqlite"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "finly_data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
